### ISSUE TITLE
Provide Selector?

### ISSUE THREAD

**Issue by thorbenandresen** [salsita/redux-saga-rxjs#5]
Do you provide a selector [similar to yield select](https://github.com/yelouafi/redux-saga/releases/tag/v0.9.0)? Or is there another handy way to achieve this kind of decoupling from the redux state?

**Comment by slorber** [comment]
@Thorbenandresen actually the "select" effect of Redux-saga is what creates coupling to Redux state. Using `select` effect was initially my proposal to avoid passiing a getState callback in every generator, but I also was against relying on getState everywhere in the first place.

Instead of considering your state as being your redux store state, you should consider it your event log instead (see https://github.com/yelouafi/redux-saga/issues/8).
Your Redux state is just a projection of your source of truth; the event log. In sagas you can create other projections, OR reuse Redux projection (but it then creates coupling, because redux state is likely to have been built for a view purpose, not flow control logic)

If you want to do this, remember that you are free to create multiple derived streams from the input stream provided to your saga.

@tomkis1 can provide better examples as I've not worked with Rx for a long time and here's one I found:

``` javascript
const dndTransaction = input$ => input$
  .filter(action => action.type === Actions.BeginDrag)
  .flatMap(action => {
    return Observable.merge(
      Observable.of({ type: Actions.Toggled, expanded: false }),
      input$
        .filter(action => action.type === Actions.EndDrag)
        .take(1)
        .map(() => ({ type: Actions.Toggled, expanded: true }))
    );
  });
```

So, you can see that you can merge 2 streams based on $input together. One can wait for the desired action to trigger the behavior, and the other can compute the state you need (by reducing the stream with a reducer you already use inside Redux for example)

In a sense, for me the Rx-based solution is less likely to create coupling between your saga and your store shape because you would tend to use only the reducer you really need for your saga (or even better: build a new one) while with redux-saga you would rely on already computed state, that was built for another purpose (but with selectors it's not such a big deal anyway)

**Comment by slorber** [comment]
@tomkis1 another idea would be that the $input stream provide both the current Redux state and the action?

**Comment by thorbenandresen** [comment]
@slorber - interesting, I certainly get the idea of it, thanks for explaining!

However I still struggle with the implementation of this.

For example I have currently two sagas :

``` js
const checkToken = iterable => iterable
  .filter(({ action }) => action.type === 'APP_STARTED')
  .flatMap(({state}) => asyncGet$('user_accessToken')
  .map(token => token === '' || token === null
    ?  ({type: 'USER_AUTH_FAILED', authed: false, accessToken: null})
    :  ({type: 'USER_AUTHED', authed: true, accessToken: token })))
```

When the app starts, I load in the user' s access token from the local storage. The token is then also stored in the redux reducer...

``` js
const queryData = iterable => iterable
  .filter(({action}) => action.type === 'USER_AUTHED' || action.type === 'FILTER_CHOSEN')
  .flatMap(({state}) => queryAPI$(state.user.get('accessToken'), action.filterValue)
    .map(json => ({ type: 'DATA_QUERIED', data: json}))
```

I then immediately query the API after the app starts. Here I could just use `action.accessToken` (instead of `state.user.get('accessToken')`) to provide the token to my the queryAPI$ function. 

However later on, the user would choose a filter which would trigger another API request, but this time, I dont have the `action.accessToken` handy, so I would need to get from the redux state. 

How could I in this scenario compute the accessToken state from the event log? I think an example like that could really help my understanding.

btw. the saga being coupled to a selector instead of being coupled to the redux state directly is what I originally meant by "this kind of decoupling from the redux state" :)

**Comment by tomkis** [comment]
> @Thorbenandresen actually the "select" effect of Redux-saga is what creates coupling to Redux state. Using select effect was initially my proposal to avoid passiing a getState callback in every generator, but I also was against relying on getState everywhere in the first place.

Absolutely! Avoid relying on App state when possible and @Thorbenandresen your example is actually perfect use case for the explanation.

Let me explain how it can be easily achieved using this library:

So the idea is that we can create Reducer which accumulates our access token and because Event log is single source of truth we can derive that information from two actions `USER_AUTHED` and `USER_AUTH_FAILED`:

``` javascript
const authCallbacksPredicate = ({ action }) => action.type === 'USER_AUTHED' || action.type === 'USER_AUTH_FAILED';

const authTokenReducer = input$ => input$
  .filter(authCallbacksPredicate)
  .scan((acc, { action }) => {
    switch (action.type) {
      case 'USER_AUTHED':
        return action.payload;
      case 'USER_AUTH_FAILED':
        return false;
      default:
        throw new Error('Unhandled action');
    }
  }, false);
```

As you can see we've effectively built our Rxjs friendly reducer which can be used in Sagas. Anytime you need to save some "intermediate" state [`scan`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/scan.md) operator is your friend.

Now that we have the information in Saga we can utilize [`combineLatest`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/combinelatest.md) operator to combine intermediate state (auth token) with our `fetchRequests$` where fetch request may be potentially any action which should trigger data loading (`request`):

``` javascript
const withAuthToken = (input$, fetchRequests$, request) => Observable
  .combineLatest(
    authTokenReducer(input$),
    fetchRequests$,
    (authToken, fetchRequest) => authToken // We need only authToken for API call
  )
  .filter(authToken => !!authToken) // Very important predicate which triggers request only when authToken is not falsy
  .flatMap(request);
```

Now we can easily use our `withAuthToken` function with specific `fetchRequests$` and `request` implementation:

``` javascript
const triggerFetchPredicate = ({ action }) => action.type === 'USER_AUTHED' || action.type === 'FILTER_CHOSEN';

export default input$ => withAuthToken(
  input$,
  input$.filter(triggerFetchPredicate),
  authToken => Observable.fromPromise(Api(authToken))
    .map(response => ({ type: 'DATA_QUERIED', payload: response }))
);
```

Please @Thorbenandresen let me know if that was any helpful to you.

**Comment by thorbenandresen** [comment]
thank you, that was very helpful!

So if I understand it right, then there is a quite a trade-off: 
- Spinning up a reducer function and a merge function for every state variable is a lot of code, compared to just tapping into the redux state with getState().
- Possible duplicate computation & storage of state variables due to maintaining state in two places 
- More mental overhead due to maintaining state in two different palces in two different ways (Redux state has a rich devtools ecosystem, saga-state don't)

I am now confused about the practical benefits of a total decoupling of the redux-state which would justify these trade-offs. I understand that the event-log is ultimate single source of truth and that decoupled sagas have its practical use in backend system (e.g. dealing with caching & materialized views as explained by "Turning the database inside out with Apache Samza"). But why is it practical in front-end systems where state is reseted at app start and [race-conditations don't seem to be an issue](https://github.com/reactjs/redux/blob/master/docs/introduction/ThreePrinciples.md#state-is-read-only)? 

Is it only the percieved benefit of seperation of concerns? (If you assume that redux is a projection of the event-log for managing UI, while saga-state is a projection of the event-log for managing flow-control?) I mean, why not do it both in redux and and keep  UI and flow-control in two seperate reducers? For front-end purposes, this should be then practically the same as maintaining flow-control state in a decoupled saga-state.

I am really on the fence here about which approach make more sense to go forward with, so 
@slorber @tomkis can you please clarify? 

Back to my inital question: I'd guess there are a lot of people who find more convinient to just use the Redux state, and those people might actually benefit from a selector to at least decouple from the state shape.

**Comment by slorber** [comment]
@Thorbenandresen sorry for long delay, wanted to answer but don't know enough RxJS these times to be helpful...

> Possible duplicate computation & storage of state variables due to maintaining state in two places

You can easily memoize reducers: [https://github.com/slorber/rereduce](https://github.com/slorber/rereduce) (the "reducer dependency system" is not something I'd use in production, just a test I did)

> I mean, why not do it both in redux and keep UI and flow-control in two seperate reducers? 

This is perfectly fine to me, if you succeed to make a clear demarcation of which state of your redux store belongs to which component / saga. However, not allowing the saga to use at all anything from the Redux store will permit to avoid anyone starting to depend on a state slice he should not.

> Back to my inital question: I'd guess there are a lot of people who find more convinient to just use the Redux state, and those people might actually benefit from a selector to at least decouple from the state shape.

Even if I would not use it, I thing @tomkis1 it could be helpful if your $input was a stream of (event,reduxStoreState), so that people can decide themselves if they want to rely on existing UI state, or build saga states by scanning events.

---

@Thorbenandresen I think nobody currently has any clear answer to this. What I know sf that in backend systems, bounded contexts and sagas are decoupled:
- Often a saga or a bounded context is used as boundaries for the perimeter of a microservice. 
- One should be able to update in production a bounded context or a saga without having to touch more than 1 microservice in most cases.
- One microservice (or bounded context / saga) should not share its database with another microservice.

For devops, it can be convenient to let's say, use a single MongoDB for 2 microservices. Each of the microservices can then only access the slice of state it computes itself (ie each mongodb has its own set of collections), and should not query the slice of states of other microservices directly. If one microservice has to depend on data of another microservice, it would then query it through a public API.

In frontend we are just starting to do something similar IMHO, where widgets are like microservices and compute their state slices in reducers of the Redux store.

The only problem is that there is not yet any clear demarcation of the boundaries of these widgets. In Redux you can easily access from anywhere the state of any widget. If your widget has a selector, it is a selector meant to be used as a public API, or for internal widget use only? (in both case it's exported, unless your selector is in same file as the jsx component)

Also is it better if the saga query widgets through their public API to know how to behave, or if it computes its own state? I think this question is valid for both frontend or backend world. There are less constraints for frontend because code runs in same computer but i'd rather have sagas that have no public api dependency when this is possible. If my saga could run inside a webworker that would be perfect for me.

**Comment by slorber** [comment]
Just for linking purpose,
- Similar issue in redux-saga: https://github.com/yelouafi/redux-saga/issues/43
- Twitter discussion; https://twitter.com/sebastienlorber/status/715189748524920833

**Comment by tomkis** [comment]
@Thorbenandresen

> Spinning up a reducer function and a merge function for every state variable is a lot of code, compared to just tapping into the redux state with getState().

Question is though... Is that really a drawback? Your control logic flow state doesn't necessarily need to be bound to your View... imagine you want to swap View implementation therefore change shape of the State, it should not affect implemented Sagas.

> Possible duplicate computation & storage of state variables due to maintaining state in two places

As @slorber has already mentioned, you can always use something like https://github.com/slorber/rereduce to avoid unnecessary performance overhead... though I am more than convinced that for most cases this might potentially be an overkill. 

> More mental overhead due to maintaining state in two different palces in two different ways (Redux state has a rich devtools ecosystem, saga-state don't)

Good thing about Streams is that it eliminates State... see the example above, the state is there but it's hidden in Stream itself no need to reason about it.

Besides, Saga **always** holds some kind of State and it's actually FSM because [Generators/Streams are just high level abstraction of FSM](https://twitter.com/YassineElouafi2/status/702866672642879488), what would you do if you didn't have Saga? You'd need to keep that FSM in your app state and we want to avoid that, because this is in my opinion the main benefit of Saga. It completely abstracts away orchestration of long running transaction while polluting your View specific application state by intermediate state of some long running transaction is definitely not ideal.

In other words... saying that all state should be in one place is no longer a valid statement on the other hand, the less we have to think about state the better.

> I am now confused about the practical benefits of a total decoupling of the redux-state which would justify these trade-offs

Decoupling like in any architecture gives us better maintainability, scalability and extendability. Like I said, you can re-write your views / reducers without touching Sagas. Using Selectors you'd still need to keep them in mind because they deny the fact that Event log is single source of truth.

> Back to my inital question: I'd guess there are a lot of people who find more convinient to just use the Redux state, and those people might actually benefit from a selector to at least decouple from the state shape.

Let's build a simple Functor:

``` javascript
const selector = (fn, ...args) => input => ({ ...input, state: fn(input.state, ...args) });
```

Now you can use it as follows:

``` javascript
const someGreatSelector = appState => ({ foo: appState.bar });

const saga = input$ => input$
  .filter(actionPredicate)
  .map(selector(someGreatSelector))
  .flatMap(({ action, state }) => {
    // state is unwrapped here using `someGreatSelector`
   });
```

**Comment by slorber** [comment]
@tomkis1 I don't understand how it works. 

Do you mean that $input provided by this lib should inject objects of type {action,state}? 
I find it fine then.

 Not sure it's a good idea, but maybe it can be put in userland as a helper function? don't know if you can easily access redux store reducer and memoize/reuse it with an api like that?

```
const saga = input$ => withReduxStoreState(input$)
  .filter(actionPredicate)
  .map(selector(someGreatSelector))
  .flatMap(({ action, state }) => {
    // state is unwrapped here using `someGreatSelector`
   });
```

**Comment by tomkis** [comment]
> Do you mean that $input provided by this lib should inject objects of type {action,state}? 
> I find it fine then.

@slorber it does provide that already https://github.com/salsita/redux-saga-rxjs/issues/1#issuecomment-184716986

> Not sure it's a good idea, but maybe it can be put in userland as a helper function? don't know if you can easily access redux store reducer and memoize/reuse it with an api like that?

Would need to think about your proposal using `withReduxStoreState` but currently can't really imagine sane implementation of this.

**Comment by slorber** [comment]
ooh ok @tomkis1 I didn't remember that input stream was `{action,state}` then `withReduxStoreState` does not make much sense to me anymore.

So basically you can only provide a little utility function here, but @Thorbenandresen already have everything he needs to solve his problem I think:

``` javascript
const saga = input$ => input$
  .filter(actionPredicate(FILTER_CHOSEN))
  .map(selector({authToken: authTokenSelector}))
  .flatMap(({authToken}) => queryAPI$(authToken, action.filterValue)
    .map(json => ({ type: 'DATA_QUERIED', data: json}))
```

@tomkis1 I think it's more easy to manage with this map of selectors because it's more natural if you can rename the state key to something else (like authToken here). In a sense it's closer to `mapStateToProps` of Redux actually, but it's just a matter of taste I guess... See also my Redux-related proposal here (that you can comment too btw :p): https://github.com/reactjs/react-redux/pull/323

**Comment by thorbenandresen** [comment]
> Good thing about Streams is that it eliminates State... see the example above, the state is there but it's hidden in Stream itself no need to reason about it.

[...]

> It completely abstracts away orchestration of long running transaction while polluting your View specific application state by intermediate state of some long running transaction is definitely not ideal.
> 
> In other words... saying that all state should be in one place is no longer a valid statement on the other hand, the less we have to think about state the better.

Ah yes, I get it now, that makes a lot of sense! Thanks for clarification, I now replaced all my getState() with saga reducers. 

@tomkis1 @slorber thanks for all great the comments, I learned a lot here.

**Comment by tomkis** [comment]
> @tomkis1 I think it's more easy to manage with this map of selectors because it's more natural if you can rename the state key to something else (like authToken here). In a sense it's closer to mapStateToProps of Redux actually, but it's just a matter of taste I guess... See also my Redux-related proposal here (that you can comment too btw :p): reactjs/react-redux#323

I definitely like it! I found myself facing exactly the same problem like you are... 

> @tomkis1 @slorber thanks for all great the comments, I learned a lot here.

All credits goes to @slorber he's great at explaining saga related stuff ;-)

**Comment by slorber** [comment]
haha thanks :)

I'm not so used to sagas and DDD but we are currently building the foundations of our next backend and it starts to become clearer as I'm working on it with someone experienced with these :)

**Comment by thorbenandresen** [comment]
@tomkis1  I have a quick question. In the following code I load my `filterOptions` object into the `filterOptionsReducer` upon  `'APP_STARTED'`.  Later on in the code I am then modifying the filterOptions object in the `prepareFilterSave` Function. Everything works great if I would execute this function only once. If I execute it again, it will of course give me the stale version of the `filterOptions` object which existed upon `APP_STARTED`

So my question is: How can I update the `filterOptions` in the `filterOptionsReducer` upon `'FILTER_SAVE_PREPARED'`?

``` js
const filterOptionsReducer = input$ => input$
  .filter(({action}) => action.type === 'APP_STARTED' ) 
  .do(() => console.log('START FilterOptionsReducerPredicate'))
  .scan((acc, { action }) => {
    switch (action.type) {
      case 'APP_STARTED':
        return action.filterOptions
      default:
        throw new Error('Unhandled action')
    }
  }, false)



  const withFilterOptions = (input$, fetchRequests$, request) => Observable
  .combineLatest(
    filterOptionsReducer(input$),
    fetchRequests$,
    (filterOptions, {action}) => ({action ,filterOptions})
  )
  .flatMap(request)



  const prepareFilterSavePredicate = ({ action }) =>  action.type === 'FILTER_DELETE_REQUESTED'  || action.type === 'FILTER_DEFAULT_SET' || action.type === 'FILTER_ADD_REQUESTED'


  const prepareFilterSave = input$ => withFilterOptions(
  input$,
  input$.filter(prepareFilterSavePredicate),
  ({action, filterOptions}) =>  Observable.of({action, filterOptions})
  .map(({action, filterOptions}) => { 

                 switch (action.type) {
                    case 'FILTER_DELETE_REQUESTED':
                        return filterOptions.filter(options => options.get('filterId') !== action.filterId) 
                    case 'FILTER_DEFAULT_SET':
                        return filterOptions.map(options => options.get('filterId') === action.filterId
                                ? options.set('default', true)
                                : options.set('default', false))
                    case 'FILTER_ADD_REQUESTED':
                        return filterOptions.insert(0, Immutable.fromJS({
                                filterId: filterOptions.reduce((maxId, filter) => Math.max(filter.get('filterId'), maxId), -1) + 1,
                                filterType: action.filterType,
                                filterValue: action.filterValue,
                                filterOperator: action.filterOperator,
                                filterUnit: action.filterUnit
                                }))
                    default:
                        break;
                }})
  .map((filterOptions) => ({type:'FILTER_SAVE_PREPARED', filterOptions })))

```

this here would not work as it creates a circular reference...

``` js
const filterOptionsReducer = input$ => input$
  .filter(({action}) => action.type === 'APP_STARTED'  || action.type === 'FILTER_SAVE_PREPARED') 
  .do(() => console.log('START FilterOptionsReducerPredicate'))
  .scan((acc, { action }) => {
    switch (action.type) {
      case 'FILTER_SAVE_PREPARED':
      case 'APP_STARTED':
        return action.filterOptions
      default:
        throw new Error('Unhandled action')
    }
  }, false)
```

**Comment by thorbenandresen** [comment]
@tomkis1 sorry, sometimes the solution becomes so obvious right after you press `Comment` :)

The answer is of course to use the reducer like you do in Redux:

``` js
const filterOptionsReducerPredicate = ({ action }) => action.type === 'APP_STARTED' || action.type === 'FILTER_DELETE_REQUESTED'  || action.type === 'FILTER_DEFAULT_SET' || action.type === 'FILTER_ADD_REQUESTED'

const filterOptionsReducer = input$ => input$
  .filter(filterOptionsReducerPredicate)
  .scan((acc, { action }) => {
    switch (action.type) {
      case 'APP_STARTED':
        return action.filterOptions
      case 'FILTER_DELETE_REQUESTED':
        return acc.filter(options => options.get('filterId') !== action.filterId) 
      case 'FILTER_DEFAULT_SET':
        return acc.map(options => options.get('filterId') === action.filterId
                ? options.set('default', true)
                : options.set('default', false))
      case 'FILTER_ADD_REQUESTED':
        return acc.insert(0, Immutable.fromJS({
                filterId: acc.reduce((maxId, filter) => Math.max(filter.get('filterId'), maxId), -1) + 1,
                filterType: action.filterType,
                filterValue: action.filterValue,
                filterOperator: action.filterOperator,
                filterUnit: action.filterUnit
                }))
      default:
        throw new Error('Unhandled action')
    }
  }, false)

  const withFilterOptions = (input$, fetchRequests$, request) => Observable
  .combineLatest(
    filterOptionsReducer(input$),
    fetchRequests$,
    (filterOptions, {action}) => ({action ,filterOptions}) 
  )
  .flatMap(request)



  const prepareFilterSavePredicate = ({ action }) =>  action.type === 'FILTER_DELETE_REQUESTED'  || action.type === 'FILTER_DEFAULT_SET' || action.type === 'FILTER_ADD_REQUESTED'

  const prepareFilterSave = input$ => withFilterOptions(
  input$,
  input$.filter(prepareFilterSavePredicate),
  ({filterOptions}) =>  helperData.asyncSet$('user_filters', JSON.stringify(filterOptions))
        .map(() => ({ type: 'FILTERS_SAVED', filterOptions: filterOptions }))) 

```

However this raises one question:

I have now two identical reducers, doing the same computations: 1) in Redux (to change the local redux state) & 2) in Sagas (to save that change to AsyncStorage)

Is this a design flaw on my part, or is this just the trade-off of decoupling Sagas from Redux?

**Comment by tomkis** [comment]
The question is though? Are they really same? Because if they are you could potentially use the same implementation - keep in mind that either way, reducer is just a function.
